# This is a basic workflow to help you get started with Actions

name: Check build for Arch.

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  arch-build:
    container: archlinux:latest
    runs-on: ubuntu-latest
    env:
      PACKAGES: meson gtk3 gobject-introspection vala json-glib libhandy gtk-layer-shell scdoc
    steps:
      - name: Install packages
        run: |
          pacman-key --init
          pacman -Sy --noconfirm $PACKAGES

      - name: Check out sources
        uses: actions/checkout@v3

      - name: Meson configure
        run: meson build

      - name: Build
        run: ninja -C build
