# This is a basic workflow to help you get started with Actions

name: Building

on: [push, pull_request, workflow_dispatch]

jobs:
  ubuntu:
    runs-on: ubuntu-21.10
    steps:
      - uses: actions/checkout@v2
      - name: Apt update
        run: sudo apt update
      - name: Install depends
        run: sudo apt install meson libwayland-dev libgtk-3-dev gobject-introspection libgirepository1.0-dev valac libjson-glib-dev libhandy-1-dev libgtk-layer-shell-dev
      - name: Meson
        run: meson build
      - name: Build
        run: ninja -C build
