# This is a basic workflow to help you get started with Actions

name: Linting

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  vala-linting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: elementary/actions/vala-lint@master
      with:
        dir: src/
        conf: .vala-lint.conf
        fail: true

  rpmlint:
    container: registry.fedoraproject.org/fedora-minimal:latest
    runs-on: ubuntu-latest
    steps:
      - name: Install rpmlint
        run: |
          microdnf -y install --nodocs --setopt=install_weak_deps=0 \
            rpmlint rpkg

      - name: Check out sources
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: swaync

      - name: Copy spec into root dir
        run: |
          cd swaync
          cp ./build-scripts/swaync.rpkg.spec ./

      - name: Generate spec
        run: |
          cd swaync
          mkdir -p specs
          rpkg spec --source --outdir specs

      - name: Start linting
        run: |
          cd swaync
          rpmlint ./specs/swaync.rpkg.spec
