# This is a basic workflow to help you get started with Actions

name: Check build for latest Ubuntu LTS.

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  ubuntu-LTS-build:
    container: ubuntu:22.04
    runs-on: ubuntu-latest
    env:
      DEBIAN_FRONTEND: noninteractive
      PACKAGES: meson libwayland-dev libgtk-3-dev gobject-introspection libgirepository1.0-dev valac libjson-glib-dev libhandy-1-dev libgtk-layer-shell-dev scdoc libgee-0.8-dev libpulse-dev sassc
    steps:
      - name: Install packages
        run: |
          apt update
          apt install -y $PACKAGES

      - name: Check out sources
        uses: actions/checkout@v3

      - name: Meson configure
        run: meson build

      - name: Build
        run: ninja -C build
